version: "3"
services:
  irc_server:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
      - "5432:5432"
    tty: true
    stdin_open: true
    volumes:
      - .:/app/
