#!/usr/bin/expect

log_user 0
# Variables (replace these with your actual credentials and server info)
set timeout 1
set server localhost
set port 1234
set nick testbot 
set username testbot
set realname "testbot"
set password wrong_pass

# Start nc connected to the IRC server
spawn nc $server $port

send "PASS $password\r"
expect  {
    "*Password is incorrect*" {
    }
    timeout {
        send_user "KO\r\n"
        exit
    }
}

close

spawn nc $server $port

send "NICK $nick\r"
expect  {
    "*Password is incorrect*" {
    }
    timeout {
        send_user "KO\r\n"
        exit
    }
}
close

spawn nc $server $port
send "USER $username 0 * :$realname\r"
expect  {
    "*Password is incorrect*" {
    }
    timeout {
        send_user "KO\r\n"
        exit
    }
}

send_user "OK\r\n"


